# Generated by Django 5.1 on 2024-08-28 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duvida', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Dúvidas',
            },
        ),
        migrations.CreateModel(
            name='Investidor',
            fields=[
                ('id_investidor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('datanasc', models.DateField()),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Investidores',
            },
        ),
        migrations.CreateModel(
            name='Corretora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('avaliacao', models.FloatField()),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.investidor')),
            ],
            options={
                'verbose_name_plural': 'Corretoras',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('relato_feedback', models.TextField()),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.investidor')),
            ],
            options={
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='PerfilInvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_investido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=50)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.investidor')),
            ],
            options={
                'verbose_name_plural': 'Perfis de Investimento',
            },
        ),
        migrations.CreateModel(
            name='Seguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('dicas', models.TextField()),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.investidor')),
            ],
            options={
                'verbose_name_plural': 'Seguranças',
            },
        ),
        migrations.CreateModel(
            name='TipoInvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_investimento', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('relato', models.TextField()),
                ('dicas', models.TextField()),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.investidor')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Investimentos',
            },
        ),
    ]
