# Generated by Django 5.1 on 2024-08-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilinvest',
            name='capital_investido',
        ),
        migrations.RemoveField(
            model_name='perfilinvest',
            name='id',
        ),
        migrations.AddField(
            model_name='perfilinvest',
            name='id_capitalinvest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, primary_key=True, serialize=False),
        ),
    ]
