# Generated by Django 5.1 on 2024-08-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_perfilinvest_capital_investido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilinvest',
            name='id_capitalinvest',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, primary_key=True, serialize=False),
        ),
    ]
