# Generated by Django 5.1.1 on 2024-09-26 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_topico_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='topico',
        ),
        migrations.RemoveField(
            model_name='topico',
            name='conteudo',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
